### ISSUE TITLE
User Edit Page

### ISSUE THREAD

**Issue by syorito-hatsuki** [PDaI-Group-12/frontend#10]

**Comment by Deforested** [comment]
![Image](https://github.com/user-attachments/assets/6f0c711b-b731-4ac0-b474-a9b15ba76752)
 First draft of the edit page

**Comment by Deforested** [comment]
![Image](https://github.com/user-attachments/assets/7ecda99a-611b-426a-bed6-ca4d55bc419c)
Second draft of the edit page

**Comment by Deforested** [comment]
![Image](https://github.com/user-attachments/assets/10248c71-3c93-412f-ab1d-c4ba41a31faf)
Third draft of the edit page

**Comment by syorito-hatsuki** [comment]
|Button|Corner Button|Floating Action Button|
|-|-|-|
|![image](https://github.com/user-attachments/assets/2517c90b-268a-4f5f-b421-af1fc255310b)|![image](https://github.com/user-attachments/assets/e71a2142-1619-4262-b9ce-f344027ecc00)|![image](https://github.com/user-attachments/assets/cf1790d9-abd4-4b0f-966c-92a806768528)|

**Comment by syorito-hatsuki** [comment]
End selection is **Floating Action Button**

**Comment by syorito-hatsuki** [comment]
Next step is fix 10 todos

**Comment by vima20** [comment]
userRouter.put('/edituser/:userid')
