### ISSUE TITLE
Save hours page

### ISSUE THREAD

**Issue by Deforested** [PDaI-Group-12/frontend#15]
Page that opens after logging in where worker can add their hours/permanent salaries.

**Comment by Deforested** [comment]
![Image](https://github.com/user-attachments/assets/d50c52d4-975e-42f6-9b32-fb870b03c1cd)
Initial state of the page after user opens it

**Comment by vima20** [comment]
'/addhours'
'/addpermanentsalary'
Nämä tehty backendin puolelle.
